use phylax_common::{Error, Result};
use crate::{AlertProvider, AlertContext};
use lettre::{
    message::{header::ContentType, Message, Mailbox},
    transport::smtp::authentication::Credentials,
    SmtpTransport, Transport,
};
use std::sync::Arc;

pub struct EmailProvider {
    smtp_server: String,
    smtp_port: u16,
    username: String,
    password: String,
    from_address: String,
    to_addresses: Vec<String>,
    use_tls: bool,
}

impl EmailProvider {
    pub fn new(
        smtp_server: String,
        smtp_port: u16,
        username: String,
        password: String,
        from_address: String,
        to_addresses: Vec<String>,
        use_tls: bool,
    ) -> Self {
        EmailProvider {
            smtp_server,
            smtp_port,
            username,
            password,
            from_address,
            to_addresses,
            use_tls,
        }
    }

    fn build_email_body(&self, context: &AlertContext) -> String {
        format!(
            "Security Alert: {}\n\n\
             Severity: {}\n\
             Event ID: {}\n\
             Rule: {}\n\
             Threat Level: {}\n\n\
             Description: {}\n\n\
             This alert was generated by Phylax security platform.",
            context.title,
            context.severity.as_str(),
            context.event_id,
            context.decision.rule_name,
            context.decision.threat_level.as_str(),
            context.description.as_deref().unwrap_or("No description provided")
        )
    }
}

#[async_trait::async_trait]
impl AlertProvider for EmailProvider {
    async fn send_alert(&self, context: &AlertContext) -> Result<()> {
        let from_mailbox: Mailbox = self.from_address
            .parse()
            .map_err(|e| Error::AlertError(format!("Invalid from address: {}", e)))?;

        let email = Message::builder()
            .from(from_mailbox)
            .subject(&format!("[Phylax Alert] {}", context.title))
            .header(ContentType::TEXT_PLAIN)
            .body(self.build_email_body(context))
            .map_err(|e| Error::AlertError(format!("Failed to build email: {}", e)))?;

        let creds = Credentials::new(self.username.clone(), self.password.clone());

        let mailer = if self.use_tls {
            SmtpTransport::relay(&self.smtp_server)
                .map_err(|e| Error::AlertError(format!("Failed to create mailer: {}", e)))?
                .port(self.smtp_port)
                .credentials(creds)
                .build()
        } else {
            SmtpTransport::builder_dangerous(&self.smtp_server)
                .port(self.smtp_port)
                .credentials(creds)
                .build()
        };

        for to_address in &self.to_addresses {
            let to_mailbox: Mailbox = to_address
                .parse()
                .map_err(|e| Error::AlertError(format!("Invalid to address: {}", e)))?;

            let email_with_to = email.clone().to(to_mailbox);

            mailer.send(&email_with_to)
                .map_err(|e| Error::AlertError(format!("Failed to send email: {}", e)))?;
        }

        Ok(())
    }

    fn provider_name(&self) -> &'static str {
        "email"
    }
}
